default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mini_helpdesk_development
test:
  <<: *default
  database: mini_helpdesk_test
production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>